package io.github.opencubicchunks.cubicchunks.mixin.core.common.world.level.cube;

import io.github.opencubicchunks.cubicchunks.world.level.chunklike.ImposterProtoClo;
import io.github.opencubicchunks.cubicchunks.world.level.chunklike.LevelClo;
import io.github.opencubicchunks.cubicchunks.world.level.cube.ImposterProtoCube;
import io.github.opencubicchunks.cubicchunks.world.level.cube.LevelCube;
import org.spongepowered.asm.mixin.Dynamic;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;

// Needed for DASM to apply
@Mixin(ImposterProtoCube.class)
public abstract class MixinImposterProtoCube extends MixinProtoCube implements ImposterProtoClo {
    // Field generated by DASM
    @Dynamic @Shadow @Final private LevelCube wrapped;

    @Override public LevelClo cc_getWrappedClo() {
        return this.wrapped;
    }
}
