name: cleanupJob.yml
on:
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete temporary artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: post-build-state
