name: Java CI

on:
  push:
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up git submodules
        run: git submodule init && git submodule update
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build -x test -x longRunTest

      - name: Tar post-build state
        run: tar --exclude=./post-build.tar.gz -czf post-build.tar.gz .
      - name: Upload post-build state
        uses: actions/upload-artifact@v4
        with:
          name: post-build-state
          path: .

      - name: Upload compiled jars
        uses: actions/upload-artifact@v4
        with:
          name: compiled-jars
          path: build/libs/*.jar

  call-test:
    needs: build
    uses: ./.github/workflows/testJob.yml
    with:
      name: 'test'
      command: './gradlew check -x longRunTest'

  call-longRunTest:
    needs: build
    uses: ./.github/workflows/testJob.yml
    with:
      name: 'longRunTest'
      command: './gradlew check -x test'

  call-cleanup:
    needs: [ call-test, call-longRunTest ]
    uses: ./.github/workflows/cleanupJob.yml
